name: lk3rd CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Disable man-db update
      run: sudo rm -f /var/lib/man-db/auto-update

    - name: Update apt mirrors
      run: sudo apt update
      
    - name: Install dependencies
      run: sudo apt install build-essential g++-aarch64-linux-gnu gcc-aarch64-linux-gnu python-is-python3 python3 wget

    - name: Install mkbootimg
      run: wget https://raw.githubusercontent.com/kdrag0n/kramflash/refs/heads/master/mkbootimg.py && sudo ln -sf $(pwd)/mkbootimg.py /usr/bin/mkbootimg && chmod +x /usr/bin/mkbootimg

    - name: Build the project for all devices
      run: ./build.sh all -v y

    - name: Upload boot images and tar files
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          boot-*.img
          *.tar
